# Generated by Django 3.1.2 on 2020-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConfLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('platform', models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('Jitsi Meet', 'Jitsi Meet')], max_length=256)),
            ],
        ),
    ]
