# Generated by Django 3.1.2 on 2020-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_videoconflinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconflinks',
            name='platform',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('Jitsi Meet', 'Jitsi Meet'), ('MS Teams', 'MS Teams')], max_length=256),
        ),
    ]
